language: cpp

before_script:
  - ./autogen.sh
    --disable-dependency-tracking
    --with-jpeg-includes=$JPEG/include
    --with-jpeg-libraries=$JPEG/lib
  - cat config.log
  - echo PKG_CONFIG_PATH = $PKG_CONFIG_PATH
  - echo which pkg-config ; which pkg-config
  - pkg-config --list-all
  - pkg-config --debug libpng
  - make -j$JOBS -s V=0
script:
  - make -Ctest -j$JOBS -s V=0 VERBOSE=1 check

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      dist: precise
      env:
        - PYTHON=/usr/bin/python
        - JPEG=/usr
        - JOBS=`nproc`
        - LIBTOOLFLAGS=--quiet
      cache: ccache
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y
          automake gtk-doc-tools
          gobject-introspection
          libfftw3-dev libjpeg-turbo8-dev
          libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
          swig libmagick++-dev bc
          libcfitsio3-dev libgsl0-dev libmatio-dev
          liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
          librsvg2-dev libgif-dev
          libpango1.0-dev
          python-dev

    - os: linux
      sudo: required
      dist: trusty
      env:
        - PYTHON=/usr/bin/python
        - JPEG=/usr
        - JOBS=`nproc`
      cache: ccache
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y
          automake gtk-doc-tools
          gobject-introspection
          libfftw3-dev libjpeg-turbo8-dev
          libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
          swig libmagick++-dev bc
          libcfitsio3-dev libgsl0-dev libmatio-dev
          liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
          librsvg2-dev libgif-dev
          libpango1.0-dev libgsf-1-dev libopenslide-dev
          python-dev python-gi-dev libgirepository1.0-dev

    - os: osx
      osx_image: xcode7.3
      env:
        - PYTHON=/usr/local/bin/python
        - JPEG=/usr/local/opt/mozjpeg
        - JOBS="`sysctl -n hw.ncpu`"
        - PATH="/usr/local/opt/ccache/libexec:$PATH"
      cache: ccache
      before_install:
        - brew tap homebrew/science
        - brew update
        - brew install ccache pkg-config automake
        - brew install --ignore-dependencies gtk-doc
        - brew install
          gobject-introspection
          fftw mozjpeg libexif
          libpng webp libtiff
          swig imagemagick
          cfitsio libmatio
          orc little-cms2 poppler
          pango libgsf openslide
          librsvg giflib openexr
          python pygobject3
